const errorCodes = {
  REQUEST_SUCCESSFUL: 200,
  REQUEST_CREATED: 201,
  INVALID_DATA: 400,
  FORBIDDEN_ERROR: 403,
  NOT_FOUND: 404,
  UNAUTHORIZED_ERROR: 401,
  SERVER_ERROR: 500,
};

module.exports = errorCodes;
